### ISSUE TITLE
How to install and get started?

### ISSUE THREAD

**Issue by hadifarnoud** [qlassiqa/qWorkflow#3]
Your documentation left out the installation process. how do I install it?

**Comment by qlassiqa** [comment]
There is nothing to install, because this is just a code library.. you need AlfredApp and then you call this library from within your own Alfred workflows. Again, the only thing you need installed is Alfred, then it's just a matter of using my code library.

**Comment by hadifarnoud** [comment]
I don't understand where to start by reading your documentation. An example would be a good Getting Started help

**Comment by qlassiqa** [comment]
This github code library is ~only~ for AlfredApp users. If you don't have Alfred, you can't use this.. And all Alfred users who are able to create their own workflows will know how to use this library, so there is no getting started or installation, I'm sorry :(

**Comment by qlassiqa** [comment]
And you also need to know AppleScript to be able to use it within AlfredApp.. otherwise it's of no use to you if you don't have Alfred & know the AppleScript programming language :(

**Comment by hadifarnoud** [comment]
I do have Alfred mate. LOL. I did write two workflow and I have no clue

**Comment by qlassiqa** [comment]
Well, in that case the best way to find out how to use my code library is by importing the example workflows posted here on github - these example workflows already use my library (that's their purpose, to show you how to use my library), so looking at the example workflows' source code will get you started :)

**Comment by qlassiqa** [comment]
(also make sure that you look at the full documentation on github, not the one on the homepage, because it contains source code examples on how to use each part of the library)
